name: On push versioned release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  go-push-versioned-release:
    name: On push versioned release job
    runs-on: ubuntu-latest

    steps:
      - name: Title
        run: |
          echo "On push versioned release"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make go version tag
        uses: chronocosm/version-tag@v1

      - name: Make mutable tag
        env:
          GITHUB_AUTHENTICATION_TOKEN: ${{ secrets.CHRONOCOSM_GITHUB_ACCESS_TOKEN }}
        uses: chronocosm/mutable-tag@v1
